In [1]:
import numpy as np

In [6]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array
x4 = np.random.randint(10, size=(3, 4, 5, 6)) # Four-dimensional array

In [3]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [7]:
x1

array([5, 0, 3, 3, 7, 9])

In [9]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [10]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [11]:
x4

array([[[[4, 3, 4, 4, 8, 4],
         [3, 7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5, 0],
         [1, 2, 4, 2, 0, 3],
         [2, 0, 7, 5, 9, 0]],

        [[2, 7, 2, 9, 2, 3],
         [3, 2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8, 2],
         [3, 0, 0, 6, 0, 6],
         [3, 3, 8, 8, 8, 2]],

        [[3, 2, 0, 8, 8, 3],
         [8, 2, 8, 4, 3, 0],
         [4, 3, 6, 9, 8, 0],
         [8, 5, 9, 0, 9, 6],
         [5, 3, 1, 8, 0, 4]],

        [[9, 6, 5, 7, 8, 8],
         [9, 2, 8, 6, 6, 9],
         [1, 6, 8, 8, 3, 2],
         [3, 6, 3, 6, 5, 7],
         [0, 8, 4, 6, 5, 8]]],


       [[[2, 3, 9, 7, 5, 3],
         [4, 5, 3, 3, 7, 9],
         [9, 9, 7, 3, 2, 3],
         [9, 7, 7, 5, 1, 2],
         [2, 8, 1, 5, 8, 4]],

        [[0, 2, 5, 5, 0, 8],
         [1, 1, 0, 3, 8, 8],
         [4, 4, 0, 9, 3, 7],
         [3, 2, 1, 1, 2, 1],
         [4, 2, 5, 5, 5, 2]],

        [[5, 7, 7, 6, 1, 6],
         [7, 2, 3, 1, 9, 5],
         [9, 9, 2, 0, 9, 1],
         [9, 0, 6, 0, 4, 8],


In [12]:
print("x4 ndim: ", x4.ndim)
print("x4 shape:", x4.shape)
print("x4 size: ", x4.size)

x4 ndim:  4
x4 shape: (3, 4, 5, 6)
x4 size:  360
